SELECT * FROM BOARD_COMMENT;
SELECT * FROM BOARD;

--대댓글추가 : 댓글번호를 참조해서 insert할 것
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'stuv','좋은 정보가 어디에...?',21,2,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'efgh','하하하...안보이시는구나...',21,2,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'wxyz','얼씨구..',21,2,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'wxyz','저는 보입니다.',21,2,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'hijk','뭐임....',21,1,DEFAULT);

SELECT * 
FROM (SELECT * FROM BOARD JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF
	WHERE BOARD_NO=21)
START WITH  BOARD_COMMENT_LEVEL=1
CONNECT BY PRIOR BOARD_COMMENT_NO=BOARD_COMMENT_REF